feat(#104): Markdown linter config for ignoring link titles
Automattic/harper pull request #305
Opened 2024-12-06 19:27 UTC by grantlemons

- **feat(#104): process links as unlintable (not as a config option yet)**
- **feat(#104): add config options to markdown struct**
- **feat(#104): propagate markdown config options through project**

Scaffolds for future markdown config options

2025-01-03 14:47 UTC, elijah-potter requested changes

2025-01-03 14:47 UTC, elijah-potter commented on harper-core/src/parsers/markdown.rs
> +pub struct Markdown(MarkdownOptions);
Try to avoid tuple structs. Even if they seem attractive at first glance, it's much more readable to refer to a field name than an index..

2025-01-03 14:47 UTC, elijah-potter commented on harper-core/src/parsers/markdown.rs
> +#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
Moving forward, I'd like to separate out all complex types into their own files. Don't make it part of this PR though, just a heads up.

2025-01-03 14:47 UTC, elijah-potter commented on harper-core/src/parsers/markdown.rs
> +    fn link_title_unlintable() {
Love it.

2025-01-03 14:47 UTC, elijah-potter commented on harper-ls/src/config.rs
> +        if let Some(v) = value.get("markdown") {
Update the [relevant page](https://writewithharper.com/docs/integrations/neovim) about how this config works. You may need to merge `master` in.

2025-01-03 14:47 UTC, elijah-potter commented on harper-comments/src/comment_parsers/unit.rs
> +    markdown_parser: Markdown,
Might it be prudent to make this generic? Allow it to accept any kind of parser, and continue to pass in `Markdown` where you already do?

2025-01-14 19:04 UTC, elijah-potter requested changes
Just a couple more little things. Good work!

2025-01-14 19:04 UTC, elijah-potter commented on packages/web/src/routes/docs/integrations/neovim/+page.md
> +For example, the title of a link is linted by default, but this behavior can be changed through the `ignore_link_title` key:
I would link to the issue that prompted the feature to be added.

2025-01-15 01:22 UTC, grantlemons commented on packages/web/src/routes/docs/integrations/neovim/+page.md
> +For example, the title of a link is linted by default, but this behavior can be changed through the `ignore_link_title` key:
I don't agree, I don't feel like its relevent considering the section is about markdown-specific config and not ignore-link-title.

2025-01-15 17:17 UTC, merged